name: quest-mirror
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jq
  - sed
  - coreutils
  - curl
  - unzip
  - git
  - meson
  - ninja
  - pkg-config
  - sdl2
  - ffmpeg
  - libusb
  - openjdk=17
  - pip
  - pip:
      - requests
